runtime: php55
api_version: 1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 1000ms
  max_pending_latency: automatic

handlers:
- url: /
  script: index.php
- url: /([a-z]+\.php)$
  script: \1
